jdbc:
  password: postgres
  username: postgres
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
hibernate:
  format_sql: 'true'
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: 'true'