-- Пункт 2 ДЗ
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS receipt;


CREATE TABLE items
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255)  NOT NULL,
    price decimal(6, 2) NOT NULL,
    offer boolean
);

CREATE TABLE receipt
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date     TIMESTAMP NOT NULL,
    ITEMS_id INTEGER   NOT NULL,
    FOREIGN KEY (ITEMS_id) REFERENCES RECEIPT (id) ON DELETE CASCADE
);

-- Пункт 3 ДЗ
INSERT INTO items (name, price, offer)
VALUES ('Milk', 2.0, false),
       ('Apple', 3.3, true),
       ('Sausage', 5.2, false),
       ('Shrimps', 15.1, false);

INSERT INTO receipt (date, ITEMS_id)
VALUES ('2022-01-03', 1),
       ('2022-01-03', 1),
       ('2022-01-03', 2),
       ('2022-01-03', 2);

-- Пункт 4 ДЗ

SELECT *
FROM items
WHERE name LIKE 'A%';

-- Пункт 5 ДЗ

SELECT *
FROM items
WHERE ID IN (SELECT ID FROM items WHERE price > 4.0);

-- Пункт 6 ДЗ

SELECT offer, COUNT(*) as isDiscount
FROM items
GROUP BY offer
HAVING COUNT(*) >= 2;

-- Пункт 7 ДЗ

SELECT DISTINCT name, price, offer, date
FROM items
         JOIN receipt
             ON items.id = receipt.items_id;