-- liquibase formatted sql

--changeset liquibase:1
CREATE TABLE IF NOT EXISTS items
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255)  NOT NULL,
    price decimal(6, 2) NOT NULL,
    offer boolean
    );

--changeset liquibase:2
CREATE TABLE IF NOT EXISTS cardnumbers
(
    cardnumber  int   NOT NULL,
    discount  int  NOT NULL
    );

--changeset liquibase:3
INSERT INTO items (name, price, offer)
VALUES ('Milk', 2.0, false),
       ('Apple', 3.3, true),
       ('Sausage', 5.2, false),
       ('Shrimps', 15.1, false),
       ('Shrimps', 15.1, false),
       ('Bread', 1.5, false),
       ('Milk', 2.2, true);


INSERT INTO cardnumbers (cardnumber,discount)
VALUES ('1000',5),
       ('1001',5),
       ('1002',5),
       ('1234',5);